server:
  port: 8067
foo: hi! there is github's repostory
spring:
  rabbitmq:
    host: 192.168.1.100
    port: 5672
    username: mep
    password: mep
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: bus-refresh
eureka:
  client:
    service-url: 
      defaultZone: http://localhost:8060/eureka/
